import type { Metadata } from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import locations from '@/data/locations.json';
export const revalidate=86400;
export function generateStaticParams(){return locations.map((location)=>({state:location.stateSlug,slug:location.slug}))}
export async function generateMetadata({params}:{params:Promise<{state:string;slug:string}>}):Promise<Metadata>{const{state,slug}=await params;const record=locations.find((location)=>location.stateSlug===state&&location.slug===slug);return{title:`${record?.name??'Venue Record'} - Imported Record`,description:'Imported venue location record. Verify operation, official location, rooms, prices, rules, and booking directly.',alternates:{canonical:`https://nearbyescaperooms.com/${state}/${slug}`},robots:{index:false,follow:true,googleBot:{index:false,follow:true}}}}
export default async function RecordPage({params}:{params:Promise<{state:string;slug:string}>}){const{state,slug}=await params;const record=locations.find((location)=>location.stateSlug===state&&location.slug===slug);if(!record)notFound();const related=locations.filter((location)=>location.stateSlug===state&&location.slug!==slug).slice(0,3);return <>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:'https://nearbyescaperooms.com'},{'@type':'ListItem',position:2,name:record.state,item:`https://nearbyescaperooms.com/${state}`},{'@type':'ListItem',position:3,name:record.name,item:`https://nearbyescaperooms.com/${state}/${slug}`}]})}}/>
  <section className="record-hero"><div className="container"><Link className="back-link" href={`/${state}`}>← {record.state} records</Link><h1>{record.name}</h1><p>Imported coordinate record · Not a current verified venue profile</p></div></section>
  <section style={{padding:'4rem 1.5rem'}}><div className="container detail-layout"><div><h2>What this record establishes</h2><p className="detail-copy">The repository stores the name <strong>{record.name}</strong>, {record.city?`the city ${record.city}, `:'no city, '}the state {record.state}, and a latitude/longitude pair. It does not record the original source or collection date.</p><h2>What must be verified</h2><ul className="check-list"><li>Whether the business is operating and the recorded coordinate is its customer entrance</li><li>Current room lineup, themes, difficulty, duration, age and content rules</li><li>Group-size limits, accessibility, hours, availability, prices, taxes, and cancellation terms</li><li>The venue’s official or clearly authorized booking path</li></ul><div className="source-warning"><strong>Do not book from this record alone.</strong> Find a current official venue source and confirm the date, location, total price, and refund terms before paying.</div><h2 style={{marginTop:'2rem'}}>Recorded coordinate</h2><div className="coordinate-box"><p>{record.lat.toFixed(5)}, {record.lng.toFixed(5)}</p><p>This may not be an entrance, parking area, or current business location.</p><a className="btn btn-crimson" href={`https://www.google.com/maps?q=${record.lat},${record.lng}`} target="_blank" rel="noopener noreferrer">Inspect coordinate</a></div></div>
  <aside className="detail-panel"><h2>Record fields</h2><dl><div><dt>Name</dt><dd>{record.name}</dd></div><div><dt>City</dt><dd>{record.city||'Not recorded'}</dd></div><div><dt>State</dt><dd>{record.state}</dd></div><div><dt>Official source</dt><dd>Not recorded</dd></div><div><dt>Review date</dt><dd>Not recorded</dd></div><div><dt>Operation / booking</dt><dd>Not verified</dd></div></dl></aside></div></section>
  {related.length>0&&<section style={{background:'var(--parchment)',padding:'4rem 1.5rem'}}><div className="container"><h2>Other imported records in {record.state}</h2><div className="grid-3" style={{marginTop:'2rem'}}>{related.map((item)=><Link className="simple-card" key={`${item.stateSlug}-${item.slug}`} href={`/${item.stateSlug}/${item.slug}`}><strong>{item.name}</strong><span>Unreviewed coordinate record</span></Link>)}</div></div></section>}
</>}
