import type { Metadata } from 'next';
import Link from 'next/link';
import locations from '@/data/locations.json';
export const revalidate=86400;
function getStateName(slug:string){return locations.find((location)=>location.stateSlug===slug)?.state??slug.split('-').map((word)=>word[0].toUpperCase()+word.slice(1)).join(' ')}
export function generateStaticParams(){return Array.from(new Set(locations.map((location)=>location.stateSlug))).map((state)=>({state}))}
export async function generateMetadata({params}:{params:Promise<{state:string}>}):Promise<Metadata>{const{state}=await params;const name=getStateName(state);return{title:`Imported Escape-Room Records in ${name}`,description:`Browse imported venue names and coordinates in ${name}. Verify operation, location, rooms, prices, and booking directly.`,alternates:{canonical:`https://nearbyescaperooms.com/${state}`},robots:{index:false,follow:true,googleBot:{index:false,follow:true}}}}
export default async function StatePage({params}:{params:Promise<{state:string}>}){const{state}=await params;const name=getStateName(state);const records=locations.filter((location)=>location.stateSlug===state);return <>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:'https://nearbyescaperooms.com'},{'@type':'ListItem',position:2,name,item:`https://nearbyescaperooms.com/${state}`}]})}}/>
  <section className="route-hero"><div className="container"><Link className="back-link" href="/browse-states">← All represented states</Link><h1>Imported records in <span>{name}</span></h1><p>{records.length} coordinate {records.length===1?'record':'records'} · Not current-verified</p></div></section>
  <section style={{padding:'2.5rem 1.5rem 4rem'}}><div className="container"><div className="source-warning"><strong>Research leads only.</strong> The repository does not record the original source, collection date, venue website, operation status, rooms, prices, booking path, or review date. Confirm all details before paying.</div><div className="grid-3" style={{marginTop:'2rem'}}>{records.map((record)=><Link key={`${record.stateSlug}-${record.slug}`} href={`/${state}/${record.slug}`} style={{textDecoration:'none'}}><article className="card"><div className="card-img record-placeholder"><span>Recorded coordinate</span><strong>{record.lat.toFixed(3)}, {record.lng.toFixed(3)}</strong></div><div className="card-body"><div className="card-meta">{record.city?`${record.city}, `:''}{name}</div><h2 className="card-title">{record.name}</h2><p className="card-copy">Imported location record. Business operation and booking details are not verified.</p></div></article></Link>)}</div></div></section>
</>}
